services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  data:
