services:
  db:
    image: postgres
    container_name: auth-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  adminer:
    container_name: auth-adminer
    image: adminer
    ports:
      - "${ADMINER_PORT}:8080"

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: secret
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  data:
  grafana_data:
